docs: Favor the Admin app over the CLI to setup FastStore
vtex/faststore pull request #1454
Opened 2022-09-05 17:48 UTC by filipewl

## What's the purpose of this pull request?

Recently we've developed an Admin app for FastStore called `vtex.admin-faststore` that helps set up the store and all its dependencies. We decided to favor installing this app and going through the setup via Admin over using the CLI plugin. This is an initial attempt to update the documentation with this information.

2022-09-05 18:11 UTC, filipewl commented on apps/docs/docs/how-to-guides/platform-integration/vtex/setting-up-an-account.md
> +Once the setup completes, all dependencies needed for developing a FastStore website will have been created: `Happy coding on FastStore 🎉`.
```suggestion
Once the setup completes, all dependencies needed for developing a FastStore website will have been installed: `Happy coding on FastStore 🎉`.
```

2022-09-07 09:13 UTC, lariciamota commented on apps/docs/docs/how-to-guides/platform-integration/vtex/setting-up-an-account.md
> +1. Install the FastStore Admin app in your account:
Please add a first step `Log in to your VTEX account` before this one

2022-09-07 09:13 UTC, lariciamota commented on apps/docs/docs/how-to-guides/platform-integration/vtex/setting-up-an-account.md
> +2. Open the Admin app at `https://{workspace}--{account}.myvtex.com/admin/faststore` and follow the setup steps.
Are we recommending using a workspace (other than master) on this setup?
I only worry that people start to think that they'll need to use this specific workspace when using faststore

2022-09-08 12:55 UTC, PedroAntunesCosta requested changes
I tried to test the app, but couldn't do it. Installed the app on my workspace, but the admin path led me to an error similar to `could not find localhost:3000`. Then I ran `nextjs.store` locally and the URL led me to a store preview embedded in the admin.

I guess maybe the admin app is not fully deployed and I would not have been able to see it anyway. Otherwise maybe there are instructions missing in the doc.

2022-09-08 12:55 UTC, PedroAntunesCosta commented on apps/docs/docs/how-to-guides/platform-integration/vtex/setting-up-an-account.md
> +In this step by step, you'll install the FastStore Admin app in your account via the VTEX IO CLI.
```suggestion
In this step by step, you will install the FastStore Admin app in your account via the VTEX IO CLI.
```

2022-09-08 12:55 UTC, PedroAntunesCosta commented on apps/docs/docs/how-to-guides/platform-integration/vtex/setting-up-an-account.md
> +Once the setup completes, all dependencies needed for developing a FastStore website will have been installed: `Happy coding on FastStore 🎉`.
```suggestion
Once the setup completes, all dependencies needed for developing a FastStore website will have been installed.
```

2023-01-13 14:23 UTC, filipewl commented
Closing this as the documentation has been moved to https://github.com/vtex/faststore-docs. 

I'll open a PR there with all the suggestions, thank you!

2023-01-13 14:23 UTC, closed without merging