Third-Party Script Management Proposal
vtex/faststore pull request #1980
Opened 2023-08-24 15:22 UTC by victors1682

## What's the purpose of this pull request?
Handle third-party scripts

## How it works?
1. In the FastStore client, add a new file name `ThirdPartyScripts.ts` within the `src/scripts` directory.
2. Define a function named ThirdPartyScripts.

```
const ThirdPartyScripts = () => { 
    return (`
        console.log('testing scripts');
          `)
}
export default ThirdPartyScripts
```
The script is injected using the PartyTown framework dependency to avoid blocking the main tread

2023-08-24 16:36 UTC, victors1682 commented on packages/core/src/customizations/scripts/ThirdPartyScripts.ts
> +  return ``
That's a good point; it would be more effective to manage an array of script templates.

2023-08-29 20:14 UTC, gvc requested changes
Thank you for your contribution, but I think we need to remove logic from overrides/ThirdPartyScripts.tsx and just make it receives a bunch of components and render them.

The `src/customizations/scripts/ThirdPartyScripts.ts` should be a tsx file that returns as many components (party town scripts) nested inside a React fragment `<></>`.

2023-08-29 20:14 UTC, gvc commented on packages/core/src/customizations/GlobalOverrides.tsx
> +import ThirdPartyScripts from 'src/customizations/components/overrides/ThirdPartyScripts'
```suggestion
import ThirdPartyScriptsOverrides from 'src/customizations/components/overrides/ThirdPartyScripts'
```

2023-08-29 20:14 UTC, gvc commented on packages/core/src/customizations/GlobalOverrides.tsx
> +  ...ThirdPartyScripts.components,
```suggestion
  ...ThirdPartyScriptsOverrides.components,
```

2023-08-29 20:14 UTC, gvc commented on packages/core/src/customizations/components/overrides/ThirdPartyScripts.tsx
> +    ThirdPartyScripts: RenderThirdPartyScripts(ThirdPartyScripts),
I don't think the `RenderThirdPartyScripts` logic is the way to go. I'd rather we just receive components from the customization and then render them.

2023-09-01 13:34 UTC, gvc requested changes
Everything looks good, just a couple of renames and we're good to go!

2023-09-01 13:34 UTC, gvc commented on packages/core/src/components/ThirdPartyScripts/ThirdPartyScripts.tsx
> +import OverwriteComponents from 'src/customizations/GlobalOverrides'
```suggestion
import OverrideComponents from 'src/customizations/GlobalOverrides'
```

2023-09-01 13:34 UTC, gvc commented on packages/core/src/components/ThirdPartyScripts/ThirdPartyScripts.tsx
> +      <OverwriteComponents.ThirdPartyScripts />
```suggestion
      <OverrideComponents.ThirdPartyScripts />
```

2023-09-01 18:36 UTC, gvc approved these changes

2023-09-01 22:29 UTC, hellofanny commented on packages/core/src/components/ThirdPartyScripts/ThirdPartyScripts.tsx
>  import VTEX from './vtex'
```suggestion
import storeConfig from '../../../faststore.config'
import GoogleTagManager from './GoogleTagManager'
import VTEX from './vtex'

import OverrideComponents from 'src/customizations/GlobalOverrides'
```

2023-09-01 22:30 UTC, hellofanny approved these changes
I've tried here and LGTM! 🚀 💯 
Thanks victor for the proposal!
I'll also create a task to document this feature.

2023-09-02 00:00 UTC, batzlerg approved these changes
🚀

2023-09-04 18:20 UTC, merged