Chore: Not Available product
vtex/faststore pull request #2031
Opened 2023-09-19 15:56 UTC by eduardoformiga

## What's the purpose of this pull request?

Previously on FastStore

- https://github.com/vtex/faststore/pull/1962
> Although our lib has the [OutOfStock](https://www.faststore.dev/components/organisms/out-of-stock) component, it's not fully integrated into our application, so we will temporarily remove it until implemented.

Then after it, we decided on use a `Not Available` product option.

Also, this PR aims to deal with this issue
- https://github.com/vtex/faststore/issues/1977

## How it works?

It shows the Selector even when the product is outOfStock so that the user can change to another product sku.

## How to test it?

You can use one product with one sku available and another outOfStock option and test it.
(reach me out if you need example)

### Starters Deploy Preview

TBD

2023-09-20 22:17 UTC, gvc requested changes
I think that we should allow overriding the NotAvailableButton if the BuyButton overridable. In the very least we should have that buttons text be editable via CMS.

2023-09-20 22:17 UTC, gvc commented on packages/core/src/components/ui/ProductDetails/ProductDetailsSettings.tsx
> +        <NotAvailableButton>Not Available</NotAvailableButton>
Shouldn't this be a prop from the CMS? Or at least an overridable component?

2023-09-25 13:53 UTC, gvc approved these changes
Just a small comment :)

2023-09-25 14:46 UTC, hellofanny commented on packages/core/src/components/product/NotAvailableButton/NotAvailableButton.tsx
> +function NotAvailableButton({ children }: PropsWithChildren) {
is there a reason that we can't call it `UnavailableButton`?

2023-09-25 14:51 UTC, hellofanny approved these changes

2023-09-25 20:31 UTC, merged