Fix: duplicated ClientManyProductsQuery
vtex/faststore pull request #2429
Opened 2024-09-02 17:03 UTC by lariciamota

## What's the purpose of this pull request?

The `ClientManyProductsQuery` was being fetched twice with almost the same parameters, the only difference was the `hasOnlyDefaultSalesChannel` introduced on this [PR](https://github.com/vtex/faststore/pull/2282) and used only by the `useAuth` hook. 
It doesn't need to be sent on the `ClientManyProductsQuery`, only on the `ValidateSession` mutation.

## How it works?

It filters the `hasOnlyDefaultSalesChannel` key out of the `channel` object in the `useLocalizedVariables` before sending it on the query.

## How to test it?

Running `yarn dev` and checking on the PDP that the `ClientManyProductsQuery` is not duplicated and is not sending the `hasOnlyDefaultSalesChannel` on `channel`.
| Before | After |
| -|-|
| <img width="1167" alt="Screenshot 2024-09-02 at 14 00 24" src="https://github.com/user-attachments/assets/f697db8f-8bda-434e-bc8d-6685ef2d462b"> | <img width="1169" alt="Screenshot 2024-09-02 at 13 58 30" src="https://github.com/user-attachments/assets/78f32e0d-18b8-413b-8299-6bd467205b6e"> |
| <img width="1173" alt="Screenshot 2024-09-02 at 14 00 54" src="https://github.com/user-attachments/assets/f8f673bb-c930-4627-b3e0-f25bb7c1ea39"> | |

### Starters Deploy Preview

## References

- [Slack thread](https://vtex.slack.com/archives/C051B6LL91U/p1725284216284089)

2024-09-02 17:24 UTC, pedromtec approved these changes

2024-09-02 20:19 UTC, eduardoformiga approved these changes

2024-09-02 21:07 UTC, mateussaggin requested changes
I think it's not 100% fixed. Now the fuzzy is the only difference in the query:
Example below

<img width="189" alt="image" src="https://github.com/user-attachments/assets/d4adf7c5-4d1e-4cac-9cd0-4081c835d720">

https://github.com/user-attachments/assets/362af7cf-c888-4786-86b8-212d94ee368b

2024-09-02 21:35 UTC, lariciamota commented
> I think it's not 100% fixed. Now the fuzzy is the only difference in the query: Example below
> 
> <img alt="image" width="189" src="https://private-user-images.githubusercontent.com/2023083/363790639-d4adf7c5-4d1e-4cac-9cd0-4081c835d720.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMTMwMjIsIm5iZiI6MTcyNTMxMjcyMiwicGF0aCI6Ii8yMDIzMDgzLzM2Mzc5MDYzOS1kNGFkZjdjNS00ZDFlLTRjYWMtOWNkMC00MDgxYzgzNWQ3MjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDJUMjEzMjAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWI4ZGUxYTY1ZDYwOTBhZDRjYjJlYzUzZDg5YWE4N2E4N2I5NTgzMGZkZGNkOWI2YmVjN2RjNjM2ZGM4MzE1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AJzCUuH7FlhYN9O0vuVpBCT5XBI_-KHTHNNYLjvSQbA">

Hi! The fuzzy is being tackled in another PR that will handle the issues introduced by the fuzzy (this included)

2024-09-03 12:15 UTC, ArthurTriis1 commented on packages/core/src/sdk/session/index.ts
> + */
Thank you for description!

2024-09-03 12:15 UTC, ArthurTriis1 approved these changes

2024-09-03 12:44 UTC, lariciamota commented on packages/core/src/sdk/session/index.ts
> +export const useSession = (filter: boolean = true) => {
Good idea!

2024-09-03 13:03 UTC, pedromtec approved these changes

2024-09-03 14:36 UTC, eduardoformiga commented on packages/core/src/sdk/session/index.ts
> +export const useSession = ({ filter }: SessionOptions = { filter: true }) => {
Nice! I think in the future, if we have more fields to filter, we should pass an array of keys, but so far, it looks good to me!

2024-09-03 14:37 UTC, eduardoformiga commented on packages/core/src/sdk/session/index.ts
> + */
Nice! 💯

2024-09-03 15:15 UTC, merged

2024-09-03 15:18 UTC, hellofanny commented on packages/core/src/sdk/session/index.ts
> + */
thanks for this 🌟