feat: search product control implementations
vtex/faststore pull request #2547
Opened 2024-11-06 20:14 UTC by ramondorosario-ct

## What's the purpose of this pull request?

This PR is about the implementation of the `Quick Order` feature. Two other PRs were created, one related to the new SearchProductItemControl component and another handling all the typing.

In this PR, the new component, typing, and some logic related to the overall implementation of the feature are brought together. A small adjustment was also made to the useBuyButton hook to prevent the `SliderOver` from opening when an item is added to the cart.

Attention This PR has dependencies on PRs: #2543 and #2546.

ps: Once PR #2543 is merged, the number of changes in this PR will decrease.

Link preview: https://starter-b8rhu2zcu-vtex.vercel.app/

## Printscreens

![image](https://github.com/user-attachments/assets/c0d5cda3-ceec-4947-b794-d5aa8cd502d6)

![image](https://github.com/user-attachments/assets/4a9c3aa5-446f-4199-94bc-b1bc2fcacdf7)

ps: the "Select multiple" button is just a regular button used for visualization purposes. Once the SKUMatrix is passed, the SKUMatrix trigger will be displayed.

2024-11-12 14:44 UTC, renatamottam commented on packages/core/src/components/search/SearchProductItem/SearchProductItem.tsx
> +          skuMatrixControl: <button>Select multiple</button>,
Could you use a `fs/buttom` instead?

2025-01-13 18:34 UTC, ramondorosario-ct commented
> Achei um comportamento esquisito nos meus testes, estou usando [esse preview](https://starter-qgjp81gbs-faststore.vercel.app/) para eles.
> 
> Quando faço uma pesquisa na home o nome dos produtos retornados na pesquisa não são os mesmos que temos na loja, exemplo:
> 
> Na Loja: <img alt="Screenshot 2025-01-07 at 12 03 45" width="618" src="https://private-user-images.githubusercontent.com/51174217/401210471-a9460cf6-0287-4414-91dc-941655b63c2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3OTM1MzEsIm5iZiI6MTczNjc5MzIzMSwicGF0aCI6Ii81MTE3NDIxNy80MDEyMTA0NzEtYTk0NjBjZjYtMDI4Ny00NDE0LTkxZGMtOTQxNjU1YjYzYzJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEzVDE4MzM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMjc5ODY4N2M2Y2IxYzk3ZDViYmJjNjJiMWUxY2NlYmM1YTEwOWJmYzU1ZmVlNzlkM2UyM2Q3MGNiYWFiZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BiufJl7Q9CAj4SAMJSZ-hG8kWRnKzClM1NR5BvnMgUA">
> 
> No Preview: <img alt="Screenshot 2025-01-07 at 12 03 04" width="632" src="https://private-user-images.githubusercontent.com/51174217/401211694-85426434-e774-4d18-a2bb-7df2a92acfe0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3OTM1MzEsIm5iZiI6MTczNjc5MzIzMSwicGF0aCI6Ii81MTE3NDIxNy80MDEyMTE2OTQtODU0MjY0MzQtZTc3NC00ZDE4LWEyYmItN2RmMmE5MmFjZmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEzVDE4MzM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NWMwZmJkZjNhYTM1M2Q4N2YxODVmMTI5ODYxZmE0NmI2YTVkMTRkZmQzMDRmZjQ3OGQxZDBlZTAzMmZiOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tPUAdJByxwMe7mzDhQWRT7TghDb5ODE6xWkjEXJqb28">
> 
> Além disso nas PDPs o `QuantitySelector` do Quick Order não está aparecendo, exemplo:
> 
> No Preview: <img alt="Screenshot 2025-01-07 at 12 03 29" width="619" src="https://private-user-images.githubusercontent.com/51174217/401210269-c7ef0956-6910-44d2-93de-935958eed1f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3OTM1MzEsIm5iZiI6MTczNjc5MzIzMSwicGF0aCI6Ii81MTE3NDIxNy80MDEyMTAyNjktYzdlZjA5NTYtNjkxMC00NGQyLTkzZGUtOTM1OTU4ZWVkMWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEzVDE4MzM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhODhkYmRlMmM2Njc5YTg5MTY1MmU4ZDRkMWUyODAwZGU1YTFiMWNhZDVhZTkwMWYzNmVjN2UyZWU1ZTQ5MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vKTSXX8Jg7mdcqhSy-xpe8woGlUV5sGV3juF1qnAd4U">

Fiz os ajustes, da um confere nesse preview: https://starter-5c71ai358-vtex.vercel.app/

2025-01-29 20:13 UTC, lucasfp13 commented
@ramondorosario-ct testing the latest preview release you sent I noticed this `NaN` warning happening on mobile when I delete the default value (`1`) with an empty one before typing the new value. Probably the input validation is happening on every input change, maybe doing this on blur solve the issue.

https://github.com/user-attachments/assets/7ffdac81-1574-4fcc-9653-b2187e46538f

2025-01-31 13:06 UTC, lucasfp13 requested changes

2025-01-31 13:06 UTC, lucasfp13 commented on packages/components/src/molecules/SearchProducts/SearchProductItemContent.tsx
> +  }, [quickOrder?.enabled])
Typescript will complain about the `quickOrder` variable not being used inside the `useCallback` scope. Maybe by creating a function outside of the `SearchProductItemContent` scope can solve this, because the conditions at lines 60 and 62 will already prevent the unexpected re-renderings.

2025-01-31 13:06 UTC, lucasfp13 commented on packages/components/src/molecules/SearchProducts/SearchProductItemControl.tsx
> +  const isMobile = window.innerWidth <= 768
We can use the value from `useScreenResize` hook instead.

2025-02-03 18:00 UTC, ramondorosario-ct commented on packages/core/src/components/search/SearchProductItem/SearchProductItem.tsx
> +    unitMultiplier,
Hello @lucasfp13! So, regarding the typing, all the adjustments related to it are in another PR. That's why this PR depends on two others, but in the end, when we merge them into the feature branch, it will be resolved.

2025-02-03 18:22 UTC, ramondorosario-ct commented
https://starter-i86c5kq90-vtex.vercel.app/

2025-02-04 14:23 UTC, lucasfp13 requested changes

2025-02-04 14:23 UTC, lucasfp13 commented on packages/core/src/components/search/SearchProductItem/SearchProductItem.tsx
> +  const { isDesktop } = useScreenResize()
**suggestion**: You can use the hook directly where you need instead create props like `mobileVersion`, `isMobile`, etc.

2025-02-04 14:23 UTC, lucasfp13 commented on packages/components/src/molecules/SearchProducts/SearchProductItemControl.tsx
> +  mobileVersion: boolean
**suggestion**: You can import and use the `useScreenResize` hook values here in the `SearchProductItemControl`

2025-02-04 14:47 UTC, ramondorosario-ct commented on packages/components/src/molecules/SearchProducts/SearchProductItemControl.tsx
> +  mobileVersion: boolean
I ended up doing it this way because the hook is contained within @packages/core, I haven't seen any examples where `@packages/components` uses hooks from core. Also, when I try to import it directly from `@packages/components`, it doesn't find this method, I would have to import it via relative path:
`import useScreenResize from "../../../../core/src/sdk/ui/useScreenResize"`.

So, is there no problem importing and using it this way?

2025-02-04 19:00 UTC, lucasfp13 commented on packages/components/src/molecules/SearchProducts/SearchProductItemControl.tsx
> +  mobileVersion: boolean
Humm you're right, I forgot to look this component is from `@faststore/components`.

In this case you should define the component behavior for mobile/tablet/desktop mode using CSS the breakpoints for each case (on `@faststore/ui` styles.scss file for this component), then using conditional renderings (with `useScreenResize` hook's  values) on `@faststore/core`. Does it make sense to you?

2025-02-05 13:43 UTC, ramondorosario-ct commented on packages/components/src/molecules/SearchProducts/SearchProductItemControl.tsx
> +  mobileVersion: boolean
Done!

2025-02-10 12:52 UTC, lucasfp13 requested changes

2025-02-10 12:52 UTC, lucasfp13 commented on packages/components/src/molecules/SearchProducts/SearchProductItemControl.tsx
> +            Out of Stock
**issue (blocking)**: In `@faststore/components` we should receive all titles and messages from props to allow changing this in the component that this will be rendered.

2025-02-13 01:22 UTC, lucasfp13 approved these changes
LGTM

2025-02-14 16:28 UTC, hellofanny commented on packages/core/src/components/search/SearchProductItem/SearchProductItem.tsx
> +          // FIXME: Use SKU Matrix component
**question:**  This will be addressed in the `quick-order` branch, right?

2025-02-17 12:12 UTC, ramondorosario-ct commented on packages/core/src/components/search/SearchProductItem/SearchProductItem.tsx
> +          // FIXME: Use SKU Matrix component
Yes! More precisely in this PR: https://github.com/vtex/faststore/pull/2620

2025-03-10 17:59 UTC, hellofanny approved these changes

2025-03-10 18:01 UTC, merged