Reverting lint fix on useShippingSimulator that caused a loop
vtex/faststore pull request #429
Opened 2020-11-26 22:51 UTC by lucis

2020-11-26 22:52 UTC, klzns requested changes

2020-11-26 22:52 UTC, klzns commented on packages/gatsby-theme-store/src/components/ShippingSimulator/hooks/useShippingSimulator.ts
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Add comment explaining

2020-11-26 23:52 UTC, klzns approved these changes

2020-11-27 00:09 UTC, emersonlaurentino approved these changes

2020-11-27 00:15 UTC, tlgimenes approved these changes
Vambora que vamo

2020-11-27 00:22 UTC, merged