[WIP] Getting Started
vtex/faststore pull request #452
Opened 2021-01-06 14:32 UTC by tlgimenes

## What's the purpose of this pull request?
<em>Considering the context, what is the problem we'll solve? Where in VTEX's big picture our issue fits in? Write a tweet about the context and the problem itself.</em>

## How it works? 
<em>Tell us the role of the new feature, or component, in its context.</em>

## How to test it?
<em>Describe the steps with bullet points. Is there any external link that can be used to better test it or an example?</em> 

## References
<em>Spread the knowledge: is there any content you used to create this PR that is worth sharing?</em>  

<em>Extra tip: adding references to related issues or mentioning people important to this PR may be good for the documentation and reviewing process</em>

2021-01-06 16:23 UTC, lariciamota commented on docs/wip/getting-started.md
> +Voce tambem precisa de uma conta na VTEX, a.k.a `storecomponents` e um usuario no Github
a.k.a. mesmo ou seria algo como "por exemplo"?

2021-01-06 16:23 UTC, lariciamota commented on docs/wip/getting-started.md
> +Caso voce esteja usando a Netlify como CI/CD, voce pode setar essas variaveis de ambiente diretamente no painel da Netlify.
Será que seria bom mostrar onde/como exatamente?

2021-01-06 16:23 UTC, lariciamota commented on docs/wip/getting-started.md
> +
Talvez aqui antes de falar sobre a versão de produção, só deixar claro que a de desenvolvimento é por http://localhost:8000/ e que as mudanças ficam sendo escutadas

2021-01-06 16:23 UTC, lariciamota commented on docs/wip/getting-started.md
> +Crie o PR. Apos o PR criado, voce vai ver os Bots validando e trabalhando no PR. Apos todos os checks terminarem com sucesso, mergeie o PR.
Não sei se em algum lugar vai ter sobre que validações são essas, mas seria bom uma mini introdução ai só para explicar o que seria "bots validando" e "checks".

2021-01-06 16:31 UTC, lariciamota commented on docs/wip/getting-started.md
React?

2021-01-06 17:55 UTC, tlgimenes commented on docs/wip/getting-started.md
> +Voce tambem precisa de uma conta na VTEX, a.k.a `storecomponents` e um usuario no Github
seria por exemplo

2021-01-06 17:55 UTC, tlgimenes commented on docs/wip/getting-started.md
> +Caso voce esteja usando a Netlify como CI/CD, voce pode setar essas variaveis de ambiente diretamente no painel da Netlify.
acho que nao, So procurar na doc da netlify que eles explicam la como faz isso

2021-01-06 17:56 UTC, tlgimenes commented on docs/wip/getting-started.md
> +
Sim ! acho que vale a pena mesmo

2021-01-06 17:57 UTC, tlgimenes commented on docs/wip/getting-started.md
Para fazer o setup acho que nao. Para depois acho que sim

2021-01-06 19:26 UTC, iaronaraujo requested changes
Fiz algumas correções ortográficas, e mudei  um pouco a estrutura de algumas frases pra ficar mais "formal".

2021-01-06 19:26 UTC, iaronaraujo commented on docs/wip/getting-started.md
> +Apos instalar e setar as ferramentas acima, siga os pacos abaixo
```suggestion
Após instalar e configurar as ferramentas acima, siga os seguintes passos:
```

2021-01-06 19:26 UTC, iaronaraujo commented on docs/wip/getting-started.md
> +Va ao terminal e logue na sua conta da VTEX
```suggestion
Através do terminal, faça login com sua conta VTEX
```

2021-01-06 19:26 UTC, iaronaraujo commented on docs/wip/getting-started.md
> +### Criacao do repo no github
```suggestion
### Criação do reposotório no github
```

2021-01-06 19:26 UTC, iaronaraujo commented on docs/wip/getting-started.md
> +Agora vamos criar o repositorio no github. Va em https://github.com/vtex-sites e clique em `new`
```suggestion
Agora vamos criar o repositório no github. Va em https://github.com/vtex-sites e clique em `new`
```

2021-01-06 19:26 UTC, iaronaraujo commented on docs/wip/getting-started.md
> +Crie o repositorio com o nome `<account>.store` a partir do template da storecomponents. Voce devera ter uma tela parecida com:
```suggestion
Crie o repositório com o nome `<account>.store` a partir do template da storecomponents. Voce devera ter uma tela parecida com:
```

2021-01-06 19:26 UTC, iaronaraujo commented on docs/wip/getting-started.md
> +Se voce nao for usar o CMS da VTEX, remove o plugin `@vtex/gatsby-plugin-cms` do `package.json` da sua loja e va para a proxima etapa.
```suggestion
Caso não vá utilizar o CMS da VTEX, remova o plugin `@vtex/gatsby-plugin-cms` do `package.json` da sua loja e vá para a proxima etapa.
```

2021-01-06 19:26 UTC, iaronaraujo commented on docs/wip/getting-started.md
> +Apos a chave criada, va no ambiente administrativo em `configuracoes de conta => gerenciamento da conta => perfils de acesso` e crie um novo perfil de acesso.
```suggestion
Após a chave criada, prossiga para o ambiente administrativo em `configurações de conta => gerenciamento da conta => perfils de acesso` e crie um novo perfil de acesso.
```

2021-01-06 19:26 UTC, iaronaraujo commented on docs/wip/getting-started.md
> +De o nome de `FastStore CMS` para esse novo perfil de acesso. Nesse perfil de acesso, configure os seguintes produtos e clique em `Salvar`
Precisa ser `FastStore CMS`?

2021-01-06 19:26 UTC, iaronaraujo commented on docs/wip/getting-started.md
> +Apos ter o perfil de acesso criado, associe o perfil de acesso criado com a chave appKey/appToken criada. Esse é o unico perfil de acesso que essa chave deve ter.
```suggestion
Apos ter o perfil de acesso criado, associe o perfil de acesso criado com a chave appKey/appToken criada. Esse é o único perfil de acesso que essa chave deve ter.
```

2021-01-06 19:26 UTC, iaronaraujo commented on docs/wip/getting-started.md
> +Agora com a chave associada corretamente com o perfil de acesso, voce precisa colocar a chave em uma variavel de ambiente no seu ambiente de CI/CD escolhido. As chaves precisam estar setadas nas segu
```suggestion
Agora com a chave associada corretamente com o perfil de acesso, voce precisa colocar a chave em uma variavel de ambiente no seu ambiente de CI/CD escolhido. As chaves precisam estar configuradas nas seguintes variaveis de ambiente:
```

2021-01-06 19:26 UTC, iaronaraujo commented on docs/wip/getting-started.md
> +Caso voce esteja usando a Netlify como CI/CD, voce pode setar essas variaveis de ambiente diretamente no painel da Netlify.
```suggestion
Caso você esteja usando a Netlify como CI/CD, voce pode configurar essas variaveis de ambiente diretamente no painel da Netlify. 
```

2021-01-06 19:26 UTC, iaronaraujo commented on docs/wip/getting-started.md
> +Caso voce esteja usando a Netlify como CI/CD, voce pode setar essas variaveis de ambiente diretamente no painel da Netlify.
É bom ter um link pra doc do netlify então

2021-01-06 19:26 UTC, iaronaraujo commented on docs/wip/getting-started.md
> +Caso esteja usando o CI/CD do DevTools, voce ainda nao consegue setar variaveis de ambiente por api ou dashboard. Peca no slack para o `@vini` colocar essas variaveis de ambiente na conta correta
```suggestion
Caso esteja utilizando o CI/CD da VTEX, peça para o seu contato com a VTEX fazer o pedido de configuração para o time de desenvolvimento.
```

2021-01-06 19:26 UTC, iaronaraujo commented on docs/wip/getting-started.md
> +> Nao é necessario setar essas variaveis no ambiente de desenvolvimento local se voce esta logado na conta com `vtex login`. Preste atencao que o token do `vtex login` expira e apos 24h voce vai ter
```suggestion
> Não é necessario configurar essas variaveis no ambiente de desenvolvimento local se você está logado na conta com `vtex login`. Preste atenção que o token do `vtex login` expira, e após 24h o comando `vtex login` terá de ser executado novamente para o build local voltar a funcionar.
```

2021-01-06 19:26 UTC, iaronaraujo commented on docs/wip/getting-started.md
> +Para comecar a desenvolver, clone o repositorio do github em uma pasta com:
```suggestion
Para começar a desenvolver, clone o repositorio do github em uma pasta com:
```

2021-01-06 19:26 UTC, iaronaraujo commented on docs/wip/getting-started.md
> +Instale as dependecias com
```suggestion
Instale as dependêcias com
```

2021-01-06 19:26 UTC, iaronaraujo commented on docs/wip/getting-started.md
> +Voce deveria ver uma saida parecida com:
```suggestion
Voce deveria ver uma saída parecida com:
```

2021-01-06 19:26 UTC, iaronaraujo commented on docs/wip/getting-started.md
> +Para gerar uma versao de producao do site e servi-la, voce vai precisar do `docker` instalado. O comando abaixo gera o site e serve com o `docker`
```suggestion
Para gerar uma versão de produção do site e servi-la, voce precisará do `docker` instalado. O comando abaixo gera o site e serve com o `docker`
```

2021-01-06 19:26 UTC, iaronaraujo commented on docs/wip/getting-started.md
> +faca um build de producao para gerar assets otimizados com
```suggestion
faça um build de produção para gerar assets otimizados com
```

2021-01-06 19:26 UTC, iaronaraujo commented on docs/wip/getting-started.md
> +Crie o PR. Apos o PR criado, voce vai ver os Bots validando e trabalhando no PR. Apos todos os checks terminarem com sucesso, mergeie o PR.
```suggestion
Crie o PR. Após o PR criado, você vai ver os Bots validando e trabalhando no PR. Apos todos os checks terminarem com sucesso, mergeie o PR.
```

2021-01-06 19:45 UTC, carolinamenezes commented on docs/wip/getting-started.md
> +Esse tutorial cobre o processo de setup da loja desde a criacao do repo git ate a criacao de tokens e perfils de acesso no admin. Algumas partes deste tutorial podem ser realizadas somente pelo pesso
Eu criei esse PR  https://github.com/vtex/faststore/pull/459/files  com uma versão em inglês 😢

2021-01-18 16:37 UTC, iaronaraujo commented
Closing this PR since the English version was already merged. https://github.com/vtex/faststore/pull/459

2021-01-18 16:37 UTC, closed without merging