e2e docs
vtex/faststore pull request #464
Opened 2021-01-06 20:13 UTC by vitorflg

As the tests are not ready yet, documents will still need many updates but it's a starting point :)

2021-01-07 14:11 UTC, gris requested changes

2021-01-07 14:11 UTC, gris commented on docs/e2e-testing.md
> +[Cypress](https://github.com/cypress-io/cypress) is a testing framework that provide a great experience to write end-to-end (E2E) tests for modern web applications. It's very flexible, fast, easy to
```suggestion
[Cypress](https://github.com/cypress-io/cypress) is a testing framework that provides a great experience to write end-to-end (E2E) tests for modern web applications. It's very flexible, fast, easy to use, and besides being broadly used in the JavaScript ecosystem, it works very well with Gatsby, that's why we choose it as our main tool.
```

2021-01-07 14:11 UTC, gris commented on docs/e2e-testing.md
> +Feel free to check some other alternatives and compare the trade-offs of end-to-end test tools [here](https://stackshare.io/cypress/alternatives).
Do you think that is necessary?

2021-01-14 22:21 UTC, carolinamenezes commented on docs/e2e-testing.md
> +
```suggestion

>ℹ️ *This test checks how our SFJ store behaves when it receives "Eyeglasses" as an input in our search bar.*

>ℹ️ *To build your own tests, we strongly encourage you to check Cypress's [guides](https://docs.cypress.io/guides/getting-started/writing-your-first-test.html#Add-a-test-file), [examples](https://docs.cypress.io/examples/examples/recipes.html#Fundamentals), [API reference](https://docs.cypress.io/api/api/table-of-contents.html), and [best practices](https://docs.cypress.io/guides/references/best-practices.html).*

```

2021-01-14 22:21 UTC, carolinamenezes commented on docs/e2e-testing.md
> +3. Run `npm run test:e2e` and verify if all tests are passing.
```suggestion
4. Run `npm run test:e2e` to check the status of the tests.
```

2021-01-14 22:21 UTC, carolinamenezes commented on docs/e2e-testing.md
> +[Best Practices](https://docs.cypress.io/guides/references/best-practices.html)
```suggestion
```

2021-01-14 22:21 UTC, carolinamenezes commented on docs/e2e-testing.md
> +VTEX has a hub of helper functions to make writing E2E tests easy, you can install .. (WIP)
```suggestion

That's it! Additionally, you can run `npm run coverage` (WIP) to visualize the test's code coverage.

```

2021-01-15 01:43 UTC, vitorflg commented on docs/e2e-testing.md
> +Feel free to check some other alternatives and compare the trade-offs of end-to-end test tools [here](https://stackshare.io/cypress/alternatives).
No, we can remove it!

2021-01-15 02:08 UTC, vitorflg commented on docs/e2e-testing.md
> +2. Add theses scripts into your `package.json`. `cy:open` will open the cypress [dashboard](https://www.cypress.io/dashboard) and `test:e2e` will run all the tests in the command line.
Can we keep the explanations somewhere?

2021-01-15 02:52 UTC, vitorflg commented
Thanks a lot, @carolinamenezes !!

2021-01-15 11:25 UTC, carolinamenezes commented on docs/e2e-testing.md
> +2. Add theses scripts into your `package.json`. `cy:open` will open the cypress [dashboard](https://www.cypress.io/dashboard) and `test:e2e` will run all the tests in the command line.
@vitorflg Coloquei depois do código como um callout. Você acha melhor colocar antes?

2021-01-15 17:33 UTC, carolinamenezes approved these changes

2021-01-15 18:03 UTC, gris commented on docs/e2e-testing.md
> +   ```bash
```suggestion
   ```js
```

2021-01-15 18:05 UTC, merged