Change CMS shape
vtex/faststore pull request #470
Opened 2021-01-11 21:15 UTC by tlgimenes

## What's the purpose of this pull request?
As required by CMS team, this PR changes the exported config json. 

1. The path `/page-data/_cms/contentTypes.json` was renamed to `/page-data/_cms/builderConfig.json`
2. `blocks` and `messages` were moved to the json's root 
3. A special contentTypes property was created

## How it works? 
<em>Tell us the role of the new feature, or component, in its context.</em>

## How to test it?
<em>Describe the steps with bullet points. Is there any external link that can be used to better test it or an example?</em> 

## References
<em>Spread the knowledge: is there any content you used to create this PR that is worth sharing?</em>  

<em>Extra tip: adding references to related issues or mentioning people important to this PR may be good for the documentation and reviewing process</em>

2021-01-12 14:48 UTC, mateuspontes approved these changes

2021-01-12 18:42 UTC, felippenardi requested changes

2021-01-12 18:42 UTC, felippenardi commented on packages/gatsby-plugin-cms/src/gatsby-node.ts
> +    schema: blks[k],
I'd rather not use cryptic names.

`blks` could be `blockNames` and `k` could be `blockName`

2021-01-12 18:42 UTC, felippenardi commented on packages/gatsby-plugin-cms/src/gatsby-node.ts
> +    const ct = ctypes[key]
I'd rather not use cryptic names. C types?

![](https://images-na.ssl-images-amazon.com/images/I/41zWoSMu9hL.jpg)

How about `const normalizedContentTypes = ...` and then you go for `contentTypes` inside `Object.keys` and `normalizedContentType` (in the singular) inside the `reduce`?

2021-01-14 15:22 UTC, felippenardi approved these changes

2021-01-14 16:00 UTC, merged