Add table of contents to README
vtex/faststore pull request #483
Opened 2021-01-18 16:25 UTC by gris

## What's the purpose of this pull request?
To make the docs more easily discoverable.

## How it works? 
<em>Tell us the role of the new feature, or component, in its context.</em>

## How to test it?
<em>Describe the steps with bullet points. Is there any external link that can be used to better test it or an example?</em> 

## References
<em>Spread the knowledge: is there any content you used to create this PR that is worth sharing?</em>  

<em>Extra tip: adding references to related issues or mentioning people important to this PR may be good for the documentation and reviewing process</em>

2021-01-18 16:26 UTC, klzns requested changes

2021-01-18 16:26 UTC, klzns commented on README.md
> +  - [What is JAMstack](./docs/what-is-jamstack.md)
```suggestion
  - [What is Jamstack](./docs/what-is-jamstack.md)
```

2021-01-18 16:27 UTC, klzns approved these changes

2021-01-20 13:10 UTC, merged

2021-01-20 13:10 UTC, emersonlaurentino approved these changes