Feat/regionid
vtex/faststore pull request #578
Opened 2021-03-19 23:31 UTC by emersonlaurentino

#576

2021-03-22 17:17 UTC, klzns requested changes

2021-03-22 17:17 UTC, klzns commented on packages/gatsby-theme-store/src/sdk/region/index.tsx
> +      value={{
See
https://github.com/vtex/faststore/pull/579/files/62f94a2f3c6ddec782d2100e0a52be0491ee25c4#diff-b611b43f45dd22a73e6ed0da8ae146c060bb90e54ac7d0939083ea5bab77aefe

2021-04-13 21:07 UTC, FabianaFerreira commented
@lbebber, can we close this PR? Related to #617

2021-04-16 16:29 UTC, FabianaFerreira commented
Added in #617

2021-04-16 16:29 UTC, closed without merging