iOS support in SearchControls
vtex/faststore pull request #639
Opened 2021-04-19 18:05 UTC by Gmantiqueira

## What's the purpose of this pull request?
<em>Considering the context, what is the problem we'll solve? Where in VTEX's big picture our issue fits in? Write a tweet about the context and the problem itself.</em>

## How it works? 
<em>Tell us the role of the new feature, or component, in its context.</em>

## How to test it?
<em>Describe the steps with bullet points. Is there any external link that can be used to better test it or an example?</em> 

## References
<em>Spread the knowledge: is there any content you used to create this PR that is worth sharing?</em>  

<em>Extra tip: adding references to related issues or mentioning people important to this PR may be good for the documentation and reviewing process</em>

2021-04-19 18:51 UTC, klzns requested changes

2021-04-19 18:51 UTC, klzns commented on packages/gatsby-plugin-cms/package.json
> +  "gitHead": "c4f235cb8edcddf4d26b3af2ffe2e4b7a4340089"
I think that change is not intended

2021-04-19 18:51 UTC, klzns commented on packages/gatsby-plugin-google-tag-manager/package.json
> +  "gitHead": "c4f235cb8edcddf4d26b3af2ffe2e4b7a4340089"
same

2021-05-03 18:51 UTC, FabianaFerreira approved these changes
LGTM

2021-05-03 19:09 UTC, klzns approved these changes

2021-05-03 19:11 UTC, merged