Feature/unavailable items minicart
vtex/faststore pull request #642
Opened 2021-04-22 14:44 UTC by lariciamota

## What's the purpose of this pull request?
Separate items in minicart between available and unavailable as a default behavior. 

## How it works? 
It separates items in minicart in the scenario in which items added to minicart become unavailable after changing the postal code.

## How to test it?
PR in stores

2021-04-22 19:24 UTC, FabianaFerreira approved these changes

2021-04-28 14:34 UTC, igorbrasileiro commented on packages/gatsby-theme-store/i18n/pt.json
> +  "minicart.warning.unavailable": "Este produto não pode ser entregue no endereço fornecido.",
Also

2021-04-28 14:36 UTC, igorbrasileiro commented on packages/gatsby-theme-store/src/sdk/product/useAvailability.ts
> +  product: ArrayItem<OrderFormData>
where this type ArrayItem come from?

2021-04-28 14:37 UTC, igorbrasileiro commented on packages/gatsby-theme-store/src/sdk/product/useAvailability.ts
> +export type OrderFormData = NonNullable<OrderForm>['items']
OrderForm isn't nullable anymore

2021-04-28 14:53 UTC, emersonlaurentino approved these changes

2021-04-28 15:19 UTC, igorbrasileiro commented on packages/gatsby-theme-store/src/components/Minicart/Drawer/Content.tsx
> +  data: OrderFormData
What do you think about inline it `OrderForm['items']` or change the name of this type, maybe or something like this `OrderFormItems`?

2021-04-28 15:19 UTC, igorbrasileiro commented on packages/gatsby-theme-store/src/components/Minicart/Drawer/Content.tsx
>    imageElement: React.ElementType
Use import type

2021-04-28 15:20 UTC, igorbrasileiro commented on packages/gatsby-theme-store/src/components/Minicart/Drawer/ContentItems/AvailableItems.tsx
> +import React from 'react'
Move to store-ui

2021-04-28 15:20 UTC, igorbrasileiro commented on packages/gatsby-theme-store/src/components/Minicart/Drawer/Content.tsx
>  import React from 'react'
move to store-ui

2021-04-28 15:20 UTC, igorbrasileiro requested changes
Move minciart to store ui

2021-04-28 16:16 UTC, igorbrasileiro commented on packages/gatsby-theme-store/src/components/Minicart/Drawer/ContentItems/Item.tsx
> +  imageElement: React.ElementType
Use named import,
```ts
import type { ElementType } from 'react'
```

2021-04-28 16:20 UTC, igorbrasileiro commented on packages/gatsby-theme-store/src/components/Minicart/Drawer/ContentItems/Item.tsx
> +import React from 'react'
move to store ui

2021-04-28 16:22 UTC, igorbrasileiro reviewed
Left more comments

2021-05-03 14:49 UTC, klzns requested changes

2021-05-03 14:49 UTC, klzns commented on packages/store-ui/src/Minicart/i18n/pt.ts
> +  'minicart.price.free': 'GRÁTIS',
Make it uppercase with CSS `text-transform: uppercase;`

```suggestion
  'minicart.price.free': 'Grátis',
```

2021-05-03 14:49 UTC, klzns commented on packages/store-ui/src/Minicart/Drawer/Content/index.tsx
> +            if (curr.sellingPrice === 0) {
You can check if an item is a gift reading the property `isGift`

2021-05-04 16:26 UTC, klzns approved these changes

2021-05-04 19:03 UTC, igorbrasileiro approved these changes

2021-05-05 13:40 UTC, merged