Feat | Store SDK
vtex/faststore pull request #668
Opened 2021-05-09 13:32 UTC by tlgimenes

## What's the purpose of this pull request?
<em>Considering the context, what is the problem we'll solve? Where in VTEX's big picture our issue fits in? Write a tweet about the context and the problem itself.</em>

## How it works? 
<em>Tell us the role of the new feature, or component, in its context.</em>

## How to test it?
<em>Describe the steps with bullet points. Is there any external link that can be used to better test it or an example?</em> 

## References
<em>Spread the knowledge: is there any content you used to create this PR that is worth sharing?</em>  

<em>Extra tip: adding references to related issues or mentioning people important to this PR may be good for the documentation and reviewing process</em>

2021-05-10 14:53 UTC, klzns requested changes

2021-05-10 14:53 UTC, klzns commented on packages/gatsby-plugin-graphql/package.json
> +  "gitHead": "56d52a2f03d0041562b750ab8d021821f3ff2179"
Remove

2021-05-10 14:53 UTC, klzns commented on packages/gatsby-source-vtex/package.json
> +  "gitHead": "56d52a2f03d0041562b750ab8d021821f3ff2179"
Remove

2021-05-10 14:53 UTC, klzns commented on packages/store-sdk/README.md
> +yarn add @vtex/store-ui
```suggestion
yarn add @vtex/store-sdk
```

2021-05-10 14:53 UTC, klzns commented on packages/store-sdk/src/ui/Provider.tsx
> +  const closeMinicart = () => dispatch({ type: 'CLOSE_MINICART' })
Might use useCallback so we can remove the `// eslint-disable-next-line react-hooks/exhaustive-deps`

2021-05-12 19:34 UTC, tlgimenes commented
@klzns , just added the comment.  Can you check it? Thanks!

2021-05-12 19:59 UTC, klzns commented
> @klzns , just added the comment.  Can you check it? Thanks!

Quite impressed with the detail! Looks great

2021-05-12 21:32 UTC, tlgimenes commented
@klzns, I was talking to @emersonlaurentino he was concerned on how the developer could extend the main UI context. To avoid using custom libs for state management, like recoil or redux, I tried implementing a new way of adding actions and effects to the UI's global state. 

Can you guys say what you think? I've also added some examples in the form of tests on how one could extend the global UI state

2021-05-12 22:31 UTC, emersonlaurentino requested changes
What do you think about we rename `initializer` to `initialValues`? Initializer sounds to me like an action...

2021-05-12 22:31 UTC, emersonlaurentino commented on packages/store-sdk/README.md
> +A simple, framework agnostic implementation of Commerce APIs to help you create you next React-based store with world class performance in record time
```suggestion
A simple, framework agnostic implementation of Commerce APIs to help you create your next React-based store with world class performance in record time
```

2021-05-12 22:31 UTC, emersonlaurentino commented on packages/store-sdk/package.json
> +  "description": "Hooks for creating your next component library",
component library?

2021-05-12 22:31 UTC, emersonlaurentino commented on packages/store-sdk/test/ui/Provider.test.tsx
> +test('UI PRovider: Open/Close minicart', async () => {
```suggestion
test('UI Provider: Open/Close minicart', async () => {
```

2021-05-12 22:31 UTC, emersonlaurentino commented on packages/store-sdk/test/ui/Provider.test.tsx
> +test('UI PRovider: Extend UI context', async () => {
```suggestion
test('UI Provider: Extend UI context', async () => {
```

2021-05-12 22:31 UTC, emersonlaurentino commented on packages/store-sdk/test/ui/Provider.test.tsx
> +test('UI PRovider: Extend UI context with custom data', async () => {
```suggestion
test('UI Provider: Extend UI context with custom data', async () => {
```

2021-05-13 00:17 UTC, tlgimenes commented on packages/store-sdk/package.json
> +  "description": "Hooks for creating your next component library",
should be store, thanks

2021-05-13 00:46 UTC, tlgimenes commented
> What do you think about we rename `initializer` to `initialValues`? Initializer sounds to me like an action...

I'm not sure. `InitialValues` seems like the second argument of `useReducer` hook. However this is the third. In react doc they use the `init` term. Do you prefer `init` here as well?

2021-05-13 09:26 UTC, tlgimenes commented
Just changed initializer to init, like in react docs @emersonlaurentino :)

2021-05-14 00:03 UTC, emersonlaurentino approved these changes

2021-05-14 14:45 UTC, merged