IOSF-320: Choosing Static Paths
vtex/faststore pull request #685
Opened 2021-05-18 08:47 UTC by mcfearsome

## What's the purpose of this pull request?
Add documentation around the process of customizing the static paths

## How it works? 
Analog Optical Character Recognition

## How to test it?
Dynamic Organic Processing Unit

## References
n/a

2021-05-18 08:48 UTC, mcfearsome commented
@iaronaraujo & @rafaelbac, I was unsure who I should add to review this so I am adding you 2 for guidance.

2021-05-18 15:37 UTC, eric-pigeon requested changes

2021-05-18 15:37 UTC, eric-pigeon commented on docs/static-paths.md
> +One of the core principles of [JAMStack](https://github.com/vtex/faststore/tree/master/docs/what-is-jamstack.md) is the pre-rendering, or static generation, of pages at build time. This provides arti
we're left with a

2021-05-20 14:12 UTC, eric-pigeon approved these changes

2021-06-04 20:56 UTC, mcfearsome commented
> Hey guys, what do we need to do to move this forward?

Hey @tlgimenes, sorry I have been out on PTO so haven't been available to bug anyone to actually review the content and approve it! I'd happily accept a review if you have the time.

2021-06-09 18:22 UTC, iaronaraujo approved these changes

2021-06-09 18:45 UTC, viniagostini approved these changes

2021-06-09 19:32 UTC, lariciamota requested changes
Good job!
It'd also be nice to have a review from a tech writer, I believe @Mariana-Caetano can help us with that.

2021-06-09 19:32 UTC, lariciamota commented on docs/static-paths.md
> +>ℹ️ *We are assuming you have followed the [Getting Started](https://github.com/vtex/faststore/tree/master/docs/getting-started.mb) document and have a running store.*
```suggestion
>ℹ️ *We are assuming you have followed the [Getting Started](https://github.com/vtex/faststore/tree/master/docs/getting-started.md) document and have a running store.*
```

2021-06-09 19:32 UTC, lariciamota commented on docs/static-paths.md
> +# the default static paths function.
```suggestion
// where getStaticPaths.js exports a single function
// that returns an array of strings. Note that no options
// are sent to the getStaticPaths function when used over
// the default static paths function.
```

2021-06-09 19:32 UTC, lariciamota commented on docs/static-paths.md
> +| getRedirects   | function | false     | n/a                                                                                                                | See [Managing URL Redirects](https://git
```suggestion
| getRedirects   | function | false     | n/a                                                                                                                | See [Managing URL Redirects](https://github.com/vtex/faststore/tree/master/docs/managing-url-redirects.md) |
```

2021-06-09 19:32 UTC, lariciamota commented on docs/static-paths.md
> +| ignorePaths    | string[] | false     | n/a                                                                                                                | *Can be used to exclude paths from the f
```suggestion
| ignorePaths    | string[] | false     | n/a                                                                                                                | Can be used to exclude paths from the final results returned by `getStaticPaths`                   |
```

2021-06-09 19:32 UTC, lariciamota commented on docs/static-paths.md
> +| pageTypes      | string[] | false     | `['Product', 'Department', 'Category', 'Brand', 'SubCategory',]`                                                   |
```suggestion
| pageTypes      | string[] | false     | `['Product', 'Department', 'Category', 'Brand', 'SubCategory']`                                                   |                                                                                                     |
```

2021-06-09 21:16 UTC, Mariana-Caetano approved these changes

2021-06-17 14:16 UTC, lariciamota approved these changes

2021-06-17 14:40 UTC, merged