Add CMS api redirect
vtex/faststore pull request #784
Opened 2021-06-21 21:47 UTC by felippenardi

## What's the purpose of this pull request?

Adds a redirect route for the CMS API (used on preview)

## How it works? 

The store hits `/cms-api?contentVariantId=123` and the CMS responds with the content of this variant

## How to test it?

## References

2021-06-21 21:49 UTC, felippenardi commented
It does not seem to be working yet. When I enter http://localhost:8000/cms-api/contentVariant?variantId==22baa7ac-c377-49ff-9f28-e2fabb093446 I get `Gatsby.js development 404 page`

2021-06-22 14:56 UTC, emersonlaurentino approved these changes

2021-06-22 19:29 UTC, tlgimenes requested changes
Please move this to gatsby-plugin-cms

2021-06-23 20:13 UTC, emersonlaurentino approved these changes

2021-06-24 17:46 UTC, tlgimenes requested changes
I think it's missing some proxy config for local development. The docs might help
https://www.gatsbyjs.com/docs/api-proxy/#gatsby-skip-here

2022-01-24 15:14 UTC, closed without merging