feat(store-ui): Create Badge component
vtex/faststore pull request #894
Opened 2021-08-13 12:41 UTC by victorhmp

## What's the purpose of this pull request?

## How it works? 

## How to test it?

## References

2021-08-13 12:49 UTC, victorhmp commented
Checked for stores using the current `Badge` from `theme-ui` exported by `@vtex/store-ui` and didn't find any. So the breaking change introduced in this PR doesn't require extra PRs 😄

2021-08-23 14:15 UTC, emersonlaurentino approved these changes

2021-08-23 17:03 UTC, igorbrasileiro requested changes
Nice job @victorhmp 👏 !! Left some comments

2021-08-23 17:03 UTC, igorbrasileiro commented on packages/store-ui/src/atoms/Badge/Badge.tsx
> +  children?: ReactNode
Also, i think would be a better idea to use the PropsWithChildren, what do you think about it?

```suggestion
  /**
    * ....
    */
  testId?: string
```

```tsx
  function Badge({ ... }: PropsWithChildren<BadgeProps>, ref)
```

2021-08-23 17:05 UTC, igorbrasileiro commented on packages/store-ui/src/atoms/Badge/Badge.tsx
> +  children?: ReactNode
Also props isn't appearing on the Props table on storybook
![image](https://user-images.githubusercontent.com/15680320/130487854-e56df373-44de-4f6d-94d8-279458fe94ba.png)

2021-08-23 20:32 UTC, igorbrasileiro approved these changes

2021-08-24 14:05 UTC, emersonlaurentino commented on packages/store-ui/src/atoms/Badge/Badge.tsx
>    ref: ForwardedRef<HTMLDivElement>
if you use `forwardRef` directly on function, you don't need to use type to ref.

```suggestion
  ref
```

2021-08-24 15:02 UTC, merged